// features/support/hooks.db.ts
import { BeforeAll, AfterAll, Before, setDefaultTimeout } from '@cucumber/cucumber';
import { GenericContainer, Wait } from 'testcontainers';
import oracledb from 'oracledb';
import fs from 'node:fs/promises';
import path from 'node:path';
import request from 'supertest';
import app from '../../src/app.js';
import oracleDBInstance from '../../src/db/connection_pool.js';
import config from '../../config.js';

setDefaultTimeout(180_000);

let container;

/** Ejecuta un .sql “plano” con statements DDL simples separados por ; al final de línea */
async function runSql(connection, sqlText) {
  const stmts = sqlText
    .split(/;\s*$/m)
    .map(s => s.trim())
    .filter(Boolean);
  for (const s of stmts) {
    await connection.execute(s);
  }
}

/** Deshabilita TODAS las FKs del esquema actual */
async function disableFks(conn) {
  const plsql = `
  BEGIN
    FOR c IN (
      SELECT constraint_name, table_name
      FROM user_constraints
      WHERE constraint_type = 'R' AND status = 'ENABLED'
    ) LOOP
      EXECUTE IMMEDIATE 'ALTER TABLE "'||c.table_name||'" DISABLE CONSTRAINT "'||c.constraint_name||'"';
    END LOOP;
  END;`;
  await conn.execute(plsql);
}

/** Rehabilita TODAS las FKs del esquema actual */
async function enableFks(conn) {
  const plsql = `
  BEGIN
    FOR c IN (
      SELECT constraint_name, table_name
      FROM user_constraints
      WHERE constraint_type = 'R' AND status = 'DISABLED'
    ) LOOP
      EXECUTE IMMEDIATE 'ALTER TABLE "'||c.table_name||'" ENABLE CONSTRAINT "'||c.constraint_name||'"';
    END LOOP;
  END;`;
  await conn.execute(plsql);
}

/** Trunca tablas. Ajustá el orden si no deshabilitás FKs. */
async function truncateTables(conn) {
  const tables = [
    'ADMINISTRACION_MEDICACION',
    'CICLO',
    'PROTOCOLO',
    'DROGA',
    'PACIENTE_PROFESIONAL',
    'PACIENTE',
    'PROFESIONAL',
    'VIA_ADMINISTRACION',
    'FORMA_FARMACEUTICA',
    'PROTOCOLO_PACIENTE'
  ];
  for (const t of tables) {
    try {
      await conn.execute(`TRUNCATE TABLE "${t}"`);
    } catch (e) {
      // ORA-00942: table or view does not exist → ignorar en tests
      if (e.errorNum !== 942) console.warn(`[TRUNCATE ${t}] ${e.message}`);
    }
  }
}

/**
 * Resetea TODAS las columnas IDENTITY a START WITH 1 y las convierte a BY DEFAULT.
 * Requiere que las tablas estén VACÍAS (por eso truncamos antes).
 */
async function resetIdentityColumns(conn) {
  const res = await conn.execute(
    `SELECT table_name, column_name
       FROM user_tab_identity_cols`,
    [],
    { outFormat: oracledb.OUT_FORMAT_OBJECT }
  );

  for (const row of (res.rows ?? [])) {
    const t = row.TABLE_NAME;
    const c = row.COLUMN_NAME;
    const sql = `ALTER TABLE "${t}" MODIFY ("${c}" GENERATED BY DEFAULT AS IDENTITY (START WITH 1))`;
    try {
      await conn.execute(sql);
    } catch (e) {
      console.warn(`[IDENTITY RESET ${t}.${c}] ${e.message}`);
    }
  }
  await conn.commit();
}

/** Opcional: semillas mínimas determinísticas (IDs fijos para estabilidad de tests) */
//async function seedMinimal(conn) {
//  // Ejemplos (adaptá a tus tablas reales):
//  // Usamos IDs fijos porque dejamos las identidades en BY DEFAULT.
//  await conn.execute(
//    'INSERT INTO PROFESIONAL (PROFESIONAL_ID, NOMBRE) VALUES (1001, \'Dra. Test\')'
//  ).catch(() => {});
//  await conn.execute(
//    'INSERT INTO PACIENTE (PACIENTE_ID, NOMBRE, FECHA_NAC) VALUES (2001, \'Paciente Demo\', DATE \'2015-05-01\')'
//  ).catch(() => {});
//}

/** Limpieza dura: FK off → TRUNCATE → reset IDENTITY → FK on */
async function hardClean(conn) {
  await disableFks(conn);
  await truncateTables(conn);
  await resetIdentityColumns(conn);
  await enableFks(conn);
  await conn.commit();
}

/** Arranque: contenedor Oracle + usuario + pool + schema.sql */
BeforeAll({ timeout: 200_000 }, async function () {
  container = await new GenericContainer('gvenzl/oracle-xe')
    .withEnvironment({ ORACLE_PASSWORD: config.oracle.adminPassword })
    .withExposedPorts(config.oracle.port)
    .withWaitStrategy(Wait.forLogMessage('DATABASE IS READY TO USE!'))
    .withStartupTimeout(120_000)
    .start();

  const host = container.getHost();
  const port = container.getMappedPort(config.oracle.port);
  config.oracle.connectString = `${host}:${port}/${config.oracle.service}`;

  // Conexión SYS para crear app_user
  const sysConn = await oracledb.getConnection({
    user: config.oracle.admin,
    password: config.oracle.adminPassword,
    connectString: config.oracle.connectString,
  });

  await sysConn.execute(`
    BEGIN
      EXECUTE IMMEDIATE 'DROP USER ' || :username || ' CASCADE';
    EXCEPTION WHEN OTHERS THEN NULL;
    END;`,
  { username: config.oracle.appUser }
  );

  await sysConn.execute(`CREATE USER ${config.oracle.appUser} IDENTIFIED BY ${config.oracle.userPassword}`);
  await sysConn.execute(`GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER TO ${config.oracle.appUser}`);
  await sysConn.execute(`ALTER USER ${config.oracle.appUser} QUOTA UNLIMITED ON USERS`);
  await sysConn.close();

  // Pool de la app y carga de schema
  await oracleDBInstance.init();
  const pool = oracleDBInstance.getPool();
  const conn = await pool.getConnection();

  const ddlPath = path.join(process.cwd(), 'features/support/schema.sql');
  const ddl = await fs.readFile(ddlPath, 'utf8');
  await runSql(conn, ddl);

  // Limpieza inicial (opcional, asegura arranque limpio)
  await hardClean(conn);

  await conn.close();
});

Before(async function () {
  const res = await request(app)
    .post('/auth/login-test')
    .send({ id: '2', name: 'Dr. Juan', role: 'admin' })
    .set('Accept', 'application/json');

  this.sessionCookie = res.headers['set-cookie'];
});

Before({ timeout: 60_000 }, async function () {
  const pool = oracleDBInstance.getPool();
  const conn = await pool.getConnection();
  try {
    await hardClean(conn);
    //await seedMinimal(conn); // opcional
  } finally {
    await conn.close();
  }
});

AfterAll({ timeout: 180_000 }, async function () {
  await oracleDBInstance.close();
  if (container) await container.stop();
});
