CREATE TABLE protocolo (
  protocolo_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(255),
  enfermedad VARCHAR2(255),
  linea VARCHAR2(255)
);

-- Tabla ciclo
CREATE TABLE ciclo (
  protocolo_id NUMBER NOT NULL,
  ciclo_id NUMBER NOT NULL,
  regimen NUMBER NOT NULL,
  duracion_semanas NUMBER,
  ciclo_final CHAR(1) CHECK (ciclo_final IN ('0','1')),
  repeticiones NUMBER,
  PRIMARY KEY (protocolo_id, ciclo_id, regimen),
  FOREIGN KEY (protocolo_id) REFERENCES protocolo(protocolo_id)
);

-- Tabla drogas
CREATE TABLE droga (
  id_droga NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  medicamento_id NUMBER,
  medicamento VARCHAR2(100) NOT NULL,
  presentacion VARCHAR2(100) NOT NULL,
  dosis NUMBER,
  dosis_unidad VARCHAR2(20),
  dosis_maxima NUMBER,
  dosis_maxima_unidad VARCHAR2(20)
);

-- Tabla profesional
CREATE TABLE profesional (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  datos_prof VARCHAR2(200)
);

-- Tabla paciente
CREATE TABLE paciente (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(100) NOT NULL,
  apellido VARCHAR2(100) NOT NULL,
  id_hospitalario VARCHAR2(30) NOT NULL,
  fecha_nacimiento DATE,
  peso FLOAT,
  ultima_modificacion TIMESTAMP,
  sexo CHAR(1) CHECK (sexo IN ('M','F')),
  profesional_id NUMBER,
  obra_social VARCHAR2(100),
  FOREIGN KEY (profesional_id) REFERENCES profesional(id)
);