CREATE TABLE protocolo (
  protocolo_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(255),
  enfermedad VARCHAR2(255),
  linea VARCHAR2(255)
);

-- Tabla ciclo
CREATE TABLE ciclo (
  protocolo_id NUMBER NOT NULL,
  ciclo_id NUMBER NOT NULL,
  regimen NUMBER NOT NULL,
  duracion_semanas NUMBER,
  ciclo_final CHAR(1) CHECK (ciclo_final IN ('0','1')),
  repeticiones NUMBER,
  PRIMARY KEY (protocolo_id, ciclo_id, regimen),
  FOREIGN KEY (protocolo_id) REFERENCES protocolo(protocolo_id)
);

-- Tabla drogas
CREATE TABLE droga (
  droga_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo_farmacia VARCHAR2(50),
  nombre_generico VARCHAR2(100) NOT NULL
);

CREATE TABLE via_administracion (
  via_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(100) NOT NULL,
  codigo VARCHAR2(50)
);

CREATE TABLE forma_farmaceutica (
  forma_farmaceutica_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre   VARCHAR2(100) NOT NULL,
  codigo   VARCHAR2(50)
);

-- Presentación de droga (tableta, vial, etc.)
CREATE TABLE presentacion_droga (
  presentacion_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  droga_id        NUMBER NOT NULL,
  forma_farmaceutica_id NUMBER NOT NULL,
  estado          VARCHAR2(50),
  fuerza_valor    NUMBER,
  fuerza_unidad   VARCHAR2(20),
  CONSTRAINT fk_pres_droga  FOREIGN KEY (droga_id) REFERENCES droga(droga_id),
  CONSTRAINT fk_pres_forma  FOREIGN KEY (forma_farmaceutica_id) REFERENCES forma_farmaceutica(forma_farmaceutica_id)
);

CREATE TABLE presentacion_droga_via (
  via_id          NUMBER NOT NULL,
  presentacion_id NUMBER NOT NULL,
  es_default      CHAR(1) DEFAULT '0' CHECK (es_default IN ('0','1')),
  CONSTRAINT pk_pres_droga_via PRIMARY KEY (via_id, presentacion_id),
  CONSTRAINT fk_pdv_via  FOREIGN KEY (via_id) REFERENCES via_administracion(via_id),
  CONSTRAINT fk_pdv_pres FOREIGN KEY (presentacion_id) REFERENCES presentacion_droga(presentacion_id)
);

-- Tabla administracion_medicacion
CREATE TABLE administracion_medicacion (
  id NUMBER GENERATED ALWAYS AS IDENTITY,
  protocolo_id NUMBER NOT NULL,
  ciclo_id NUMBER NOT NULL,
  regimen NUMBER NOT NULL,
  droga_id NUMBER NOT NULL,
  dosis NUMBER,
  dosis_unidad VARCHAR2(20),
  frecuencia VARCHAR2(100),
  administracion_diaria NUMBER,
  frecuencia_diaria NUMBER,
  PRIMARY KEY (protocolo_id, ciclo_id, regimen, droga_id),
  FOREIGN KEY (protocolo_id, ciclo_id, regimen) REFERENCES ciclo(protocolo_id, ciclo_id, regimen),
  FOREIGN KEY (droga_id) REFERENCES droga(droga_id)
);

-- Tabla profesional
CREATE TABLE profesional (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(100) NOT NULL,
  apellido VARCHAR2(100) NOT NULL,
  dni VARCHAR2(10) NOT NULL,
  matricula VARCHAR2(20),
  especialidad VARCHAR2(100)
);

-- Tabla paciente
CREATE TABLE paciente (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(100) NOT NULL,
  apellido VARCHAR2(100) NOT NULL,
  id_hospitalario VARCHAR2(30) NOT NULL,
  fecha_nacimiento DATE,
  peso FLOAT,
  ultima_modificacion TIMESTAMP,
  sexo CHAR(1) CHECK (sexo IN ('M','F')),
  profesional_id NUMBER,
  obra_social VARCHAR2(100),
  FOREIGN KEY (profesional_id) REFERENCES profesional(id)
);

-- Asignación de un protocolo a un paciente y su ciclo actual
CREATE TABLE protocolo_paciente (
  protocolo_paciente_id   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  paciente_id             NUMBER NOT NULL,
  protocolo_id            NUMBER NOT NULL,
  regimen                 NUMBER NOT NULL,
  ciclo_actual_id         NUMBER NOT NULL, -- referencia a ciclo.ciclo_id
  numero_ciclo            NUMBER,
  fecha_inicio            DATE,
  fecha_fin               DATE,
  estado                  VARCHAR2(50),
  profesional_id_asignador NUMBER,
  fecha_asignacion        TIMESTAMP,
  -- Índice único útil para evitar duplicados del mismo protocolo/regimen por paciente; incluye el ciclo actual
  CONSTRAINT uq_ppaciente UNIQUE (paciente_id, protocolo_id, regimen),
  -- Atención al orden: debe coincidir con el PK (protocolo_id, ciclo_id, regimen)
  CONSTRAINT fk_pp_ciclo FOREIGN KEY (protocolo_id, ciclo_actual_id, regimen)
    REFERENCES ciclo(protocolo_id, ciclo_id, regimen),
  CONSTRAINT fk_pp_paciente   FOREIGN KEY (paciente_id) REFERENCES paciente(id),
  CONSTRAINT fk_pp_prof_asig  FOREIGN KEY (profesional_id_asignador) REFERENCES profesional(id)
);

-- Relación N a N paciente ↔ profesional (equipo tratante)
CREATE TABLE paciente_profesional (
  profesional_id NUMBER NOT NULL,
  paciente_id    NUMBER NOT NULL,
  rol            VARCHAR2(50),
  CONSTRAINT pk_paciente_profesional PRIMARY KEY (profesional_id, paciente_id),
  CONSTRAINT fk_pprof_prof FOREIGN KEY (profesional_id) REFERENCES profesional(id),
  CONSTRAINT fk_pprof_pac  FOREIGN KEY (paciente_id)    REFERENCES paciente(id)
);