CREATE TABLE protocolo (
  protocolo_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(255),
  enfermedad VARCHAR2(255),
  linea VARCHAR2(255)
);

-- Tabla ciclo
CREATE TABLE ciclo (
  protocolo_id NUMBER NOT NULL,
  ciclo_id NUMBER NOT NULL,
  regimen NUMBER NOT NULL,
  duracion_semanas NUMBER,
  ciclo_final CHAR(1) CHECK (ciclo_final IN ('0','1')),
  repeticiones NUMBER,
  PRIMARY KEY (protocolo_id, ciclo_id, regimen),
  FOREIGN KEY (protocolo_id) REFERENCES protocolo(protocolo_id)
);

-- Tabla drogas
CREATE TABLE droga (
  droga_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo_farmacia VARCHAR2(50),
  nombre_generico VARCHAR2(100) NOT NULL
);

-- Tabla administracion_medicacion
CREATE TABLE administracion_medicacion (
  id NUMBER GENERATED ALWAYS AS IDENTITY,
  protocolo_id NUMBER NOT NULL,
  ciclo_id NUMBER NOT NULL,
  regimen NUMBER NOT NULL,
  droga_id NUMBER NOT NULL,
  dosis NUMBER,
  dosis_unidad VARCHAR2(20),
  frecuencia VARCHAR2(100),
  administracion_diaria NUMBER,
  frecuencia_diaria NUMBER,
  PRIMARY KEY (protocolo_id, ciclo_id, regimen, droga_id),
  FOREIGN KEY (protocolo_id, ciclo_id, regimen) REFERENCES ciclo(protocolo_id, ciclo_id, regimen),
  FOREIGN KEY (droga_id) REFERENCES droga(droga_id)
);

-- Tabla profesional
CREATE TABLE profesional (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(100) NOT NULL,
  apellido VARCHAR2(100) NOT NULL,
  dni VARCHAR2(10) NOT NULL,
  matricula VARCHAR2(20),
  especialidad VARCHAR2(100)
);

-- Tabla paciente
CREATE TABLE paciente (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(100) NOT NULL,
  apellido VARCHAR2(100) NOT NULL,
  id_hospitalario VARCHAR2(30) NOT NULL,
  fecha_nacimiento DATE,
  peso FLOAT,
  ultima_modificacion TIMESTAMP,
  sexo CHAR(1) CHECK (sexo IN ('M','F')),
  profesional_id NUMBER,
  obra_social VARCHAR2(100),
  FOREIGN KEY (profesional_id) REFERENCES profesional(id)
);