services:
  oracle:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    ports:
      - "1521:1521"
    environment:
      ORACLE_PWD: oracle
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -s system/oracle@XEPDB1 || exit 1"]
      interval: 15s
      timeout: 20s
      retries: 20

  init-oracle:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    environment:
      ORACLE_PWD: oracle
    depends_on:
      oracle:
        condition: service_healthy
    volumes:
      - ./src/db/db_init:/init
    entrypoint: /init/init_entrypoint.sh
    healthcheck:
      test: ["CMD-SHELL", "[ -f /tmp/init-ok ]"]
      interval: 10s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway
    env_file:
      - .env
    environment:
      FLYWAY_URL: jdbc:oracle:thin:@//oracle:1521/XEPDB1
      FLYWAY_USER: ${ORACLE_USER}
      FLYWAY_PASSWORD: ${ORACLE_PASSWORD}
      FLYWAY_DEFAULT_SCHEMA: ${ORACLE_USER}
      FLYWAY_BASELINE_ON_MIGRATE: true
      FLYWAY_CREATE_SCHEMAS: false
      FLYWAY_SCHEMAS: ${ORACLE_USER}
    volumes:
      - ./src/db/migrations:/flyway/sql
    depends_on:
      init-oracle:
        condition: service_healthy
    command: migrate

  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      flyway:
    command: npm run dev       
    volumes:
      - .:/app                 
      - /app/node_modules    
    environment:
      - NODE_ENV=development
      - ORACLE_CONNECT_STRING=oracle:1521/XEPDB1
