services:
  oracle:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    ports:
      - "${ORACLE_PORT}:${ORACLE_PORT}"
    environment:
      ORACLE_PWD: ${ORACLE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -s ${ORACLE_ADMIN}/${ORACLE_PASSWORD}@${ORACLE_SERVICE} || exit 1"]
      interval: 15s
      timeout: 20s
      retries: 20

  init-oracle:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    environment:
      ORACLE_CDB: ${ORACLE_CDB}
      ORACLE_ADMIN: ${ORACLE_ADMIN}
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
      ORACLE_HOST: ${ORACLE_HOST}
      ORACLE_PORT: ${ORACLE_PORT}
      ORACLE_SERVICE: ${ORACLE_SERVICE}
      ORACLE_APP_USER: ${ORACLE_APP_USER}
      ORACLE_USER_PASSWORD: ${ORACLE_USER_PASSWORD}
    depends_on:
      oracle:
        condition: service_healthy
    volumes:
      - ./src/db/db_init:/init
    entrypoint: /init/init_entrypoint.sh
    healthcheck:
      test: ["CMD-SHELL", "[ -f /tmp/init-ok ]"]
      interval: 10s
      timeout: 5s
      retries: 5

  flyway:
    image: flyway/flyway
    environment:
      FLYWAY_URL: jdbc:oracle:thin:@//${ORACLE_HOST}:${ORACLE_PORT}/${ORACLE_SERVICE}
      FLYWAY_USER: ${ORACLE_APP_USER}
      FLYWAY_PASSWORD: ${ORACLE_USER_PASSWORD}
      FLYWAY_SCHEMAS: ${ORACLE_APP_USER}
      FLYWAY_DEFAULT_SCHEMA: ${ORACLE_APP_USER}
      FLYWAY_LOCATIONS: filesystem:/flyway/sql
      FLYWAY_BASELINE_ON_MIGRATE: true
      FLYWAY_CREATE_SCHEMAS: false
    volumes:
      - ./src/db/migrations:/flyway/sql
    depends_on:
      init-oracle:
        condition: service_healthy
    command: migrate

  app:
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      flyway:
        condition: service_completed_successfully
    command: npm run dev       
    volumes:
      - .:/app                 
      - /app/node_modules
    environment:
      ORACLE_USER: ${ORACLE_APP_USER}
      ORACLE_PASSWORD: ${ORACLE_USER_PASSWORD}
      ORACLE_CONNECT_STRING: ${ORACLE_HOST}:${ORACLE_PORT}/${ORACLE_SERVICE}

