services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: dev_env
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    tty: true
    stdin_open: true
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - dev_container

networks:
  dev_container:
    external: true
    name: api-garrahan_testing_net
