FROM node:20

# Utilidades básicas
RUN apt-get update && apt-get install -y unzip curl git vim docker.io

# Dependencias globales JS
RUN npm install -g \
    jest \
    @cucumber/cucumber \
    nodemon \
    eslint \
    prettier
