FROM node:20

# Utilidades básicas
RUN apt-get update && apt-get install -y \
    unzip \
    curl \
    git \
    vim \
    docker.io \
    libreoffice \
    fonts-dejavu-core \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Dependencias globales JS
RUN npm install -g \
    jest \
    @cucumber/cucumber \
    nodemon \
    eslint \
    prettier
