-- Tabla protocolo
CREATE TABLE protocolo (
  protocolo_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(50) NOT NULL,
  enfermedad VARCHAR2(50) NOT NULL,
  linea VARCHAR2(20) NOT NULL
);

-- Tabla ciclo
CREATE TABLE ciclo (
  protocolo_id NUMBER NOT NULL,
  ciclo_id NUMBER NOT NULL,
  regimen NUMBER NOT NULL,
  duracion_semanas NUMBER,
  ciclo_final CHAR(1) CHECK (ciclo_final IN ('0','1')),
  repeticiones NUMBER,
  PRIMARY KEY (protocolo_id, ciclo_id, regimen),
  FOREIGN KEY (protocolo_id) REFERENCES protocolo(protocolo_id)
);

-- Tabla administracion_medicacion
CREATE TABLE administracion_medicacion (
  admin_id NUMBER GENERATED ALWAYS AS IDENTITY,
  protocolo_id NUMBER NOT NULL,
  ciclo_id NUMBER NOT NULL,
  regimen NUMBER NOT NULL,
  droga_id NUMBER NOT NULL,
  via_id NUMBER NOT NULL,
  fuerza_valor NUMBER,
  fuerza_unidad VARCHAR2(20),
  cantidad_dias NUMBER,
  administracion_diaria NUMBER,
  frecuencia_diaria NUMBER,
  PRIMARY KEY (protocolo_id, ciclo_id, regimen, droga_id, via_id),
  FOREIGN KEY (protocolo_id, ciclo_id, regimen) REFERENCES ciclo(protocolo_id, ciclo_id, regimen),
  FOREIGN KEY (droga_id) REFERENCES droga(droga_id)
  FOREIGN KEY (via_id) REFERENCES via_administracion(via_id)
);

-- Tabla via_administracion
CREATE TABLE via_administracion (
  via_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(100) NOT NULL,
  codigo VARCHAR2(50)
);

-- Tabla presentacion_droga_via 
CREATE TABLE presentacion_droga_via (
  via_id NUMBER NOT NULL,
  presentacion_id NUMBER NOT NULL,
  es_default BOOLEAN,
  PRIMARY KEY (via_id, presentacion_id),
  FOREIGN KEY (via_id) REFERENCES via_administracion(via_id)
  FOREIGN KEY (presentacion_id) REFERENCES droga(droga_id)
);

-- Tabla presentacion_droga
CREATE TABLE presentacion_droga (
  presentacion_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  droga_id NUMBER NOT NULL,
  forma_id NUMBER NOT NULL,
  estado VARCHAR2(50),
  fuerza_valor NUMBER,
  fuerza_unidad VARCHAR2(20),
  FOREIGN KEY (droga_id) REFERENCES droga(droga_id)
  FOREIGN KEY (forma_id) REFERENCES forma_farmaceutica(forma_id)
);

-- Tabla forma_farmaceutica
CREATE TABLE forma_farmaceutica (
  forma_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(100) NOT NULL,
  codigo VARCHAR2(50)
);

-- Tabla drogas
CREATE TABLE droga (
  droga_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo_farmacia VARCHAR2(50),
  nombre_generico VARCHAR2(100) NOT NULL
);

-- Tabla receta_detalle
CREATE TABLE receta_detalle (
  receta_id NUMBER NOT NULL,
  admin_id NUMBER NOT NULL,
  via_id NUMBER NOT NULL,
  cantidad NUMBER NOT NULL,
  dosis_diaria NUMBER,
  cantidad_dias NUMBER,
  dosis_total NUMBER,
  PRIMARY KEY (receta_id, admin_id),
  FOREIGN KEY (via_id) REFERENCES via_administracion(via_id),
  FOREIGN KEY (receta_id) REFERENCES tratamiento_paciente(id),
  FOREIGN KEY (admin_id) REFERENCES administracion_medicacion(admin_id)
):

-- Tabla receta_paciente
CREATE TABLE receta_paciente (
  receta_id NUMBER GENERATED ALWAYS AS IDENTITY,
  ciclo_id NUMBER NOT NULL,
  protocolo_id NUMBER NOT NULL,
  regimen NUMBER NOT NULL,
  paciente_id NUMBER NOT NULL,
  profesional_id NUMBER NOT NULL,
  fecha_receta DATE NOT NULL,
  estado_tratamiento VARCHAR2(100),
  peso FLOAT,
  talla FLOAT,
  superficie_corporal FLOAT,
  PRIMARY KEY (receta_id, ciclo_id, protocolo_id, regimen, paciente_id),
  FOREIGN KEY (paciente_id) REFERENCES paciente(paciente_id),
  FOREIGN KEY (protocolo_id, ciclo_id, regimen) REFERENCES ciclo(protocolo_id, ciclo_id, regimen),
  FOREIGN KEY (profesional_id) REFERENCES profesional(profesional_id)
);

-- Tabla protocolo_paciente
CREATE TABLE protocolo_paciente (
  protocolo_paciente_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  paciente_id NUMBER NOT NULL,
  protocolo_id NUMBER NOT NULL,
  regimen NUMBER NOT NULL,
  ciclo_actual_id NUMBER NOT NULL,
  numero_ciclo NUMBER,
  fecha_inicio DATE,
  fecha_fin DATE,
  estado VARCHAR2(50),
  profesional_id_asignador NUMBER,
  fecha_asignacion TIMESTAMP,
  PRIMARY KEY (protocolo_paciente_id, paciente_id, protocolo_id, regimen, ciclo_actual_id),
  FOREIGN KEY (paciente_id) REFERENCES paciente(paciente_id),
  FOREIGN KEY (protocolo_id, regimen, ciclo_actual_id) REFERENCES ciclo(protocolo_id, regimen, ciclo_id),
  FOREIGN KEY (profesional_id_asignador) REFERENCES profesional(profesional_id)
);

-- Tabla paciente_profesional 
CREATE TABLE paciente_profesional (
  profesional_id NUMBER NOT NULL,
  paciente_id NUMBER NOT NULL,
  rol VARCHAR2(50),
  PRIMARY KEY (profesional_id, paciente_id)
)

-- Tabla profesional
CREATE TABLE profesional (
  profesional_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(100) NOT NULL,
  apellido VARCHAR2(100) NOT NULL,
  dni VARCHAR2(10) NOT NULL,
  matricula VARCHAR2(20),
  especialidad VARCHAR2(100)
);

-- Tabla paciente
CREATE TABLE paciente (
  paciente_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR2(100) NOT NULL,
  apellido VARCHAR2(100) NOT NULL,
  id_hospitalario VARCHAR2(30) NOT NULL,
  fecha_nacimiento DATE,
  peso FLOAT,
  ultima_modificacion TIMESTAMP,
  sexo CHAR(1) CHECK (sexo IN ('M','F')),
  obra_social VARCHAR2(100)
);

-- Índices adicionales para búsquedas eficientes
CREATE INDEX idx_paciente_nombre ON paciente(nombre, apellido);
CREATE INDEX idx_tratamiento_paciente_fecha ON tratamiento_paciente(fecha_receta);

-- Índice para buscar protocolos por nombre
CREATE INDEX idx_protocolo_nombre ON protocolo(nombre);

-- Índice para buscar drogas por nombre
CREATE INDEX idx_drogas_nombre ON droga(nombre_generico);