const ERROR_FORMA_FARMACEUTICA_CREACION = 'Error al crear la forma farmacéutica';
const ERROR_FORMA_FARMACEUTICA_NO_ENCONTRADA = 'Forma farmacéutica no encontrada';
const ERROR_ID_FORMA_FARMACEUTICA_INVALIDO = 'ID de forma farmacéutica inválido';
const ERROR_OBTENER_FORMA_FARMACEUTICA = 'Error al obtener la forma farmacéutica';

export {
  ERROR_FORMA_FARMACEUTICA_CREACION,
  ERROR_FORMA_FARMACEUTICA_NO_ENCONTRADA,
  ERROR_ID_FORMA_FARMACEUTICA_INVALIDO,
  ERROR_OBTENER_FORMA_FARMACEUTICA,
};
