const ERROR_PROFESIONAL_NO_ENCONTRADO = 'Profesional no encontrado';
const ERROR_PROFESIONAL_CREACION = 'Error al crear el profesional';
const ERROR_DNI_NO_ENCONTRADO_CODE = 'DNI_NO_ENCONTRADO';

export { ERROR_PROFESIONAL_NO_ENCONTRADO, ERROR_PROFESIONAL_CREACION, ERROR_DNI_NO_ENCONTRADO_CODE };
