-- Si estás conectado al root (CDB$ROOT), cambiá a la PDB:
ALTER SESSION SET CONTAINER = XEPDB1;

-- Drop seguro (si existe), luego create:
BEGIN
  EXECUTE IMMEDIATE 'DROP USER APP_USER CASCADE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -01918 THEN -- ORA-01918: user does not exist
      RAISE;
    END IF;
END;
/

CREATE USER APP_USER IDENTIFIED BY app_pass
  DEFAULT TABLESPACE USERS
  QUOTA UNLIMITED ON USERS
  ACCOUNT UNLOCK;

-- Permisos mínimos para Flyway y tu app en su propio esquema
GRANT CREATE SESSION TO APP_USER;
GRANT CREATE TABLE TO APP_USER;
GRANT CREATE SEQUENCE TO APP_USER;
GRANT CREATE VIEW TO APP_USER;
GRANT CREATE TRIGGER TO APP_USER;
GRANT CREATE PROCEDURE TO APP_USER;
GRANT CREATE INDEX TO APP_USER;
