-- Cambiar a la PDB (recibida como &3)
ALTER SESSION SET CONTAINER = &3;

-- Drop seguro del usuario (recibido como &1)
BEGIN
  EXECUTE IMMEDIATE 'DROP USER ' || '&1' || ' CASCADE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -01918 THEN -- ORA-01918: user does not exist
      RAISE;
    END IF;
END;
/

-- Crear usuario con contraseña (recibida como &2)
CREATE USER &1 IDENTIFIED BY &2
  DEFAULT TABLESPACE USERS
  QUOTA UNLIMITED ON USERS
  ACCOUNT UNLOCK;

-- Permisos mínimos para Flyway y la app
GRANT CREATE SESSION TO &1;
GRANT CREATE TABLE TO &1;
GRANT CREATE SEQUENCE TO &1;
GRANT CREATE VIEW TO &1;
GRANT CREATE TRIGGER TO &1;
GRANT CREATE PROCEDURE TO &1;
GRANT CREATE INDEX TO &1;
