ALTER SESSION SET CONTAINER = XEPDB1;

BEGIN
  EXECUTE IMMEDIATE 'CREATE USER app_user IDENTIFIED BY app_pass DEFAULT TABLESPACE users QUOTA UNLIMITED ON users';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -01920 THEN -- ignora "user already exists"
      RAISE;
    END IF;
END;
/

GRANT CONNECT TO app_user;
GRANT CREATE SESSION TO app_user;
GRANT CREATE TABLE TO app_user;
GRANT CREATE SEQUENCE TO app_user;
GRANT CREATE VIEW TO app_user;
GRANT CREATE PROCEDURE TO app_user;
GRANT UNLIMITED TABLESPACE TO app_user;